### ISSUE TITLE
Any plans for Himatsubushi?

### ISSUE THREAD

**Issue by enumag** [jwgrlrrajn/higurashi-steam-sprite-mods#1]
Great work with the patches! Are you planning to make the same patch for Himatsubushi as well?

Just a little bug report. In version 1.0.1 you added a missing image for Watanagashi (CGAlt/night/si_si_ha_b1.png). This image however looks like it has the sunset filter applied instead of the night filter as the directory name suggests.

Just out of curiosity, how did you make those zoomed versions of some images? MGs sprites don't have such quality.

**Comment by jwgrlrrajn** [comment]
I'm working on Himatsubushi, but it's taking longer because of irl stuff. The zoomed versions were made using Waifu2x Caffe. Thanks for the heads up on the Watanagashi patch. I'll try to fix that asap.

**Comment by enumag** [comment]
Waifu2x looks nice, thanks! Can I help you with the patch somehow even though I don't have any photoshop skills?

**Comment by jwgrlrrajn** [comment]
Unfortunately, part of what's taking me longer with Himatsubushi is photoshopping some of the sprites. Specifically, since the PS3 version has a younger looking Rika and Mion in this episode, I'm making 3 versions of the patch. A strictly MG patch, minus PS3 only characters. A mostly MG patch, with PS3 Rika and Mion. And finally, a mostly MG patch, with modded PS3 Rika and Mion to match their MG hair color for consistency.

**Comment by enumag** [comment]
Oh... looks like MG didn't bother with younger sprites for them. That's a shame.... and a lot of work or you which I'm sadly unable to help you with. :-(

I really appriciate that you want to make these three variants. Looking forward to it!

**Comment by jwgrlrrajn** [comment]
To be fair, Ryukishi07 didn't bother with younger sprites for them either.

**Comment by enumag** [comment]
Right. Perhaps you could just create the first two options you mentioned (which should be about the same amount of work as the previous chapters) and leave the modded Rika and Mion for later?

By the way a few days ago I found out that in the PS3 graphics patch for Watanagashi there are 4 sprites missing. @Grelo and @ItaloKnox already fixed that in the PS3 patch but your steam patch has the same problem as well. The missing sprites are these:

```
night/re_si_ik_b1
night/re_si_na_b1
re_se_na_b1_zoom
re_se_wa_b1_zoom
(+ there is the issue with night/si_si_ha_b1 looking like sunset)
```

**Comment by jwgrlrrajn** [comment]
I might work on releasing the MG only patch first. It's a good idea. And, thank you. I'll look into it as soon as I can (although it might not be until May that I can get it done.)

**Comment by enumag** [comment]
Of course, take your time. Thank you for doing this.

**Comment by enumag** [comment]
Just a heads up about another thing I noticed - it looks like Kasai is getting his own MG sprite in Meakashi. When you get to update Watanagashi it would be nice to include this as well.

**Comment by jwgrlrrajn** [comment]
I'll certainly try to update any characters as they become available. It mostly depends on when I actually buy episode 5 though.

**Comment by jwgrlrrajn** [comment]
As I've fixed the Watanagashi sprite issues, and added the Himatsubushi patch, I declare this issue closed.

**Comment by enumag** [comment]
@jwgrlrrajn Awesome! Thank you very much. We have the perfect Himatsubushi version now!

**Comment by enumag** [comment]
@jwgrlrrajn Alright, two issues.

- The links for Onikakushi, Watanagashi and Tatarigoroshi patches in the new release are the links to the old versions.
- You should change which commit the second release points to to have it appear above the old release.

**Comment by enumag** [comment]
@jwgrlrrajn And one more. You added files `night/re_se_ik_b1.png` and `night/re_se_na_b1.png`. The missing ones however are `night/re_si_ik_b1.png` and `night/re_si_na_b1.png` (si instead of se).

**Comment by jwgrlrrajn** [comment]
Egads, you're right. I've reopened the issue so I remember to fix the actual files themselves when I have access to my PC. On the plus side, I think I was able to fix the links.

**Comment by enumag** [comment]
You fixed the Oni and Tata links but didn't fix the Wata link which is the essential one because the patch was significantly updated. Sorry for nitpicking. ;-}

**Comment by jwgrlrrajn** [comment]
You're fine. That was the one link I forgot about, evidently.

**Comment by jwgrlrrajn** [comment]
Had to update the version since I couldn't figure out how to change which release the tag pointed to. At any rate, I couldn't sleep, so I went ahead and fixed the Wata files and made sure all the links were updated to 1.1.1

**Comment by enumag** [comment]
@jwgrlrrajn Awesome! Everything seems to be fine now. Thank you!
